"use client";

import Link from "next/link";
import { ArrowLeft, Bot, CheckCircle2, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { COMMERCIAL_AGENTS, agentReadiness, type CommercialAgent } from "@/lib/commercial/agents";
import { QuickTutorial } from "@/components/commercial/quick-tutorial";

export default function CommercialAgentsPage() {
  const ready = COMMERCIAL_AGENTS.filter((agent) => agent.status === "ready").length;
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-8">
    <Link href="/commercial" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Voltar ao comando comercial</Link>
    <header className="rounded-2xl border border-border bg-card p-6">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-3"><Bot className="mt-1 h-6 w-6 text-primary" /><div><p className="text-sm font-medium text-primary">Agentes autônomos da metodologia</p><h1 className="mt-1 text-2xl font-bold">Inteligência com responsabilidade</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">Cada agente tem uma função, uma fonte de conhecimento, ferramentas permitidas e um limite de autonomia. O sistema recomenda primeiro; a execução automática só acontece quando for segura e autorizada.</p></div></div><div className="rounded-xl bg-primary/5 px-4 py-3 text-sm"><p className="text-xs text-muted-foreground">Prontos para validação</p><p className="mt-1 text-2xl font-bold text-primary">{ready}/{COMMERCIAL_AGENTS.length}</p></div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><Safety icon={ShieldCheck} title="Sem dados clínicos" text="Os agentes operam sobre o processo comercial, nunca sobre prontuários." /><Safety icon={LockKeyhole} title="Ações auditáveis" text="Cada proposta, aprovação e execução terá registro por conta." /><Safety icon={CheckCircle2} title="Humano no controle" text="Preço, reclamação, clínica e publicação exigem aprovação." /></div>
    </header>
    <section className="grid gap-4 md:grid-cols-2">{COMMERCIAL_AGENTS.map((agent) => <AgentCard key={agent.key} agent={agent} />)}</section>
    <section className="rounded-2xl border border-border bg-card p-6"><div className="flex items-start gap-3"><Sparkles className="mt-1 h-5 w-5 text-primary" /><div><h2 className="font-semibold">Como isso entra no cronograma</h2><p className="mt-1 text-sm text-muted-foreground">A base de conhecimento e o CRM são construídos junto com os agentes. O próximo agente a receber um fluxo completo é o de diagnóstico, seguido pelo planejamento estratégico e pelo follow-up.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-3"><Roadmap n="01" title="Contexto" text="Metodologia, onboarding, conversas e indicadores." /><Roadmap n="02" title="Recomendação" text="O agente explica o que encontrou e propõe a próxima ação." /><Roadmap n="03" title="Execução controlada" text="A equipe aprova; o CRM registra e executa o permitido." /></div></section>
    <QuickTutorial title="Como trabalhar com os agentes" steps={["Escolha o agente pela função e confira se ele está pronto ou ainda em construção.", "Leia objetivo, ferramentas permitidas, conhecimento utilizado e limite de autonomia.", "Execute pelo fluxo correspondente e confira evidências e logs na revisão.", "Aprove decisões estratégicas ou externas antes de permitir qualquer execução."]} note="Agentes sugerem e organizam; preço, publicação, reclamações e exceções continuam sob responsabilidade humana." />
  </main>;
}

function AgentCard({ agent }: { agent: CommercialAgent }) { return <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Bot className="h-5 w-5" /></span><div><h2 className="font-semibold">{agent.name}</h2><p className="mt-1 text-xs text-muted-foreground">{agentReadiness(agent)} · {agent.autonomy === "suggest" ? "Sugestão" : agent.autonomy === "approved_execution" ? "Execução aprovada" : "Automático"}</p></div></div><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${agent.status === "ready" ? "bg-emerald-500/10 text-emerald-600" : "bg-muted text-muted-foreground"}`}>{agent.status === "ready" ? "Pronto" : "Em construção"}</span></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{agent.description}</p><div className="mt-4 space-y-3 border-t border-border pt-4"><div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Objetivo</p><p className="mt-1 text-xs">{agent.purpose}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Ferramentas</p><p className="mt-1 text-xs text-muted-foreground">{agent.tools.join(" · ")}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Limite</p><p className="mt-1 text-xs text-muted-foreground">{agent.approval}</p></div></div><div className="mt-4 flex flex-wrap gap-1">{agent.knowledge.map((scope) => <span key={scope} className="rounded-md bg-muted px-2 py-1 text-[10px] text-muted-foreground">{scope}</span>)}</div><p className="mt-4 rounded-lg bg-primary/5 p-3 text-xs"><strong>Próximo passo:</strong> {agent.nextStep}</p></article> }
function Safety({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="rounded-xl border border-border bg-muted/30 p-3"><Icon className="h-4 w-4 text-primary" /><p className="mt-2 text-xs font-semibold">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{text}</p></div> }
function Roadmap({ n, title, text }: { n: string; title: string; text: string }) { return <div className="rounded-xl bg-muted/40 p-4"><span className="text-xs font-bold text-primary">{n}</span><h3 className="mt-2 text-sm font-semibold">{title}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{text}</p></div> }
