"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, LockKeyhole, Save } from "lucide-react";
import { MODULES, type ModulePermission, type PermissionModule } from "@/lib/auth/permissions";

type Member = { user_id: string; full_name: string; email: string | null; role: string };
const LABELS: Record<PermissionModule, string> = { client: "Visão do cliente", commercial: "Comercial", marketing: "Marketing", automation: "Automações", knowledge: "Base de conhecimento", reports: "Relatórios", settings: "Configurações" };

export default function PermissionsPage() {
  const [members, setMembers] = useState<Member[]>([]);
  const [selected, setSelected] = useState("");
  const [permissions, setPermissions] = useState<ModulePermission[]>([]);
  const [status, setStatus] = useState("");
  useEffect(() => { void fetch("/api/account/members", { cache: "no-store" }).then((response) => response.json()).then((data) => { const list = data.members ?? []; setMembers(list); if (list[0]) setSelected(list[0].user_id); }); }, []);
  useEffect(() => { if (!selected) return; setStatus(""); void fetch(`/api/account/members/${selected}/permissions`, { cache: "no-store" }).then((response) => response.json()).then((data) => setPermissions(data.permissions ?? [])); }, [selected]);
  const member = useMemo(() => members.find((item) => item.user_id === selected), [members, selected]);
  function value(module: PermissionModule) { return permissions.find((item) => item.module === module) ?? { module, can_view: false, can_edit: false, can_approve: false }; }
  function update(module: PermissionModule, key: keyof Omit<ModulePermission, "module">, checked: boolean) { const current = value(module); const next = { ...current, [key]: checked }; if (key === "can_edit" && checked) next.can_view = true; if (key === "can_approve" && checked) { next.can_view = true; next.can_edit = true; } if (key === "can_view" && !checked) { next.can_edit = false; next.can_approve = false; } setPermissions((old) => [...old.filter((item) => item.module !== module), next]); }
  async function save() { setStatus("Salvando…"); const response = await fetch(`/api/account/members/${selected}/permissions`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ permissions }) }); setStatus(response.ok ? "Permissões salvas." : "Não foi possível salvar. Verifique se a migration 052 foi aplicada."); }
  return <main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-8"><Link href="/settings?tab=members" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Voltar para membros</Link><header className="rounded-2xl border border-border bg-card p-6"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 h-6 w-6 text-primary" /><div><p className="text-sm font-medium text-primary">Painel administrativo</p><h1 className="mt-1 text-2xl font-bold">Permissões por usuário</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Escolha exatamente quais áreas cada pessoa pode visualizar, editar ou aprovar. Owner e admin mantêm acesso administrativo; esta matriz controla os demais usuários.</p></div></div></header><section className="rounded-2xl border border-border bg-card p-6"><label className="grid max-w-xl gap-2 text-sm font-medium">Usuário<select className="h-10 rounded-md border border-input bg-background px-3 font-normal" value={selected} onChange={(event) => setSelected(event.target.value)}>{members.map((item) => <option key={item.user_id} value={item.user_id}>{item.full_name || item.email || item.user_id} · {item.role}</option>)}</select></label>{member?.role === "admin" || member?.role === "owner" ? <p className="mt-4 rounded-lg bg-primary/5 p-3 text-sm text-muted-foreground">Este usuário é {member.role} e possui acesso administrativo completo.</p> : <><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase text-muted-foreground"><th className="pb-3">Módulo</th><th className="pb-3 text-center">Ver</th><th className="pb-3 text-center">Editar</th><th className="pb-3 text-center">Aprovar</th></tr></thead><tbody>{MODULES.map((module) => { const current = value(module); return <tr key={module} className="border-b border-border/60"><td className="py-4 font-medium">{LABELS[module]}</td>{(["can_view", "can_edit", "can_approve"] as const).map((key) => <td key={key} className="py-4 text-center"><input aria-label={`${LABELS[module]} — ${key}`} type="checkbox" checked={current[key]} onChange={(event) => update(module, key, event.target.checked)} className="size-4 accent-primary" /></td>)}</tr>; })}</tbody></table></div><div className="mt-5 flex items-center gap-3"><button onClick={save} className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><Save className="h-4 w-4" /> Salvar permissões</button>{status && <span className="text-sm text-muted-foreground">{status}</span>}</div></>}</section><section className="grid gap-3 sm:grid-cols-3"><Hint title="Ver" text="Acessa dados e telas do módulo." /><Hint title="Editar" text="Pode alterar informações e executar tarefas permitidas." /><Hint title="Aprovar" text="Pode validar ações propostas por agentes ou equipe." /></section></main>;
}

function Hint({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border border-border bg-card p-4"><Check className="h-4 w-4 text-primary" /><h2 className="mt-2 text-sm font-semibold">{title}</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{text}</p></div>; }
