"use client";
import { useEffect, useState } from 'react';

type Question = { key: string; label: string; required?: boolean };
export default function PublicDiagnosticPage({ params }: { params: Promise<{ token: string }> }) {
  const [token, setToken] = useState(''); const [title, setTitle] = useState('Diagnóstico empresarial'); const [questions, setQuestions] = useState<Question[]>([]); const [answers, setAnswers] = useState<Record<string, string>>({}); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [state, setState] = useState<'loading'|'ready'|'submitted'|'error'>('loading');
  useEffect(() => { void params.then(({ token: value }) => { setToken(value); return fetch(`/api/public/diagnostic/${value}`).then((response) => response.json()).then((body) => { if (!body.data) throw new Error(); setTitle(body.data.title); setQuestions(body.data.questions ?? []); setState('ready'); }).catch(() => setState('error')); }); }, [params]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setState('loading'); const response = await fetch(`/api/public/diagnostic/${token}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ respondent_name: name, respondent_email: email, answers }) }); setState(response.ok ? 'submitted' : 'error'); }
  if (state === 'loading') return <main className="mx-auto max-w-2xl p-6">Carregando formulário…</main>;
  if (state === 'submitted') return <main className="mx-auto max-w-2xl p-6"><section className="rounded-2xl border bg-card p-8 text-center"><h1 className="text-2xl font-bold">Respostas recebidas</h1><p className="mt-3 text-muted-foreground">Obrigado. A equipe vai revisar as informações e entrar em contato para confirmar os próximos passos.</p></section></main>;
  if (state === 'error') return <main className="mx-auto max-w-2xl p-6"><section className="rounded-2xl border bg-card p-8 text-center"><h1 className="text-2xl font-bold">Formulário indisponível</h1><p className="mt-3 text-muted-foreground">O link pode ter expirado ou já ter sido respondido.</p></section></main>;
  return <main className="mx-auto max-w-2xl space-y-6 p-4 sm:p-8"><header><p className="text-sm font-medium text-primary">Diagnóstico</p><h1 className="mt-2 text-3xl font-bold">{title}</h1><p className="mt-3 text-sm text-muted-foreground">Responda com o máximo de contexto possível. As informações serão revisadas antes de qualquer recomendação.</p></header><form onSubmit={submit} className="space-y-4"><div className="rounded-2xl border bg-card p-5"><label className="block text-sm font-medium">Seu nome<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-1 h-10 w-full rounded-md border bg-background px-3" /></label><label className="mt-4 block text-sm font-medium">E-mail<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1 h-10 w-full rounded-md border bg-background px-3" /></label></div>{questions.map((question) => <label key={question.key} className="block rounded-2xl border bg-card p-5 text-sm font-medium">{question.label}{question.required ? ' *' : ''}<textarea required={question.required} value={answers[question.key] ?? ''} onChange={(e) => setAnswers((old) => ({ ...old, [question.key]: e.target.value }))} rows={3} className="mt-2 w-full rounded-md border bg-background p-3 font-normal" /></label>)}<button type="submit" className="h-11 w-full rounded-md bg-primary px-4 font-medium text-primary-foreground">Enviar diagnóstico</button></form></main>;
}
