"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, FileText, Save, ShieldCheck, Target } from "lucide-react";
import { buildStrategyPlan, type StrategyPlan } from "@/lib/commercial/strategy-plan";

type Snapshot = { profile?: Record<string, unknown> | null; assessments?: Record<string, unknown>[] };
const box = "rounded-2xl border border-border bg-card p-6";

export default function StrategyPlanPage() {
  const [plan, setPlan] = useState<StrategyPlan>(() => buildStrategyPlan(null, null));
  const [assessmentId, setAssessmentId] = useState<string | null>(null);
  const [status, setStatus] = useState("");
  useEffect(() => { void fetch("/api/commercial/onboarding").then((response) => response.json()).then((data: Snapshot) => { const assessment = data.assessments?.[0] ?? null; setAssessmentId(typeof assessment?.id === "string" ? assessment.id : null); setPlan(buildStrategyPlan(data.profile ?? null, assessment)); }); }, []);
  async function savePlan() { setStatus("Salvando versão para revisão…"); const response = await fetch("/api/commercial/strategy-plan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assessment_id: assessmentId, plan, status: "in_review" }) }); setStatus(response.ok ? "Versão salva para revisão." : "A migration do plano ainda precisa ser aplicada no banco."); }
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8">
    <Link href="/commercial/strategy" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Voltar ao centro do plano</Link>
    <header className={box}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><FileText className="mt-1 h-7 w-7 text-primary" /><div><p className="text-sm font-medium text-primary">Documento estratégico interno</p><h1 className="mt-1 text-2xl font-bold">{plan.title}</h1><p className="mt-2 max-w-4xl text-sm leading-relaxed text-muted-foreground">Esta versão incorpora briefing, pesquisa, oferta, funil, aquisição, processo comercial, métricas, governança e plano de 90 dias. Campos sem evidência permanecem explicitamente pendentes.</p></div></div><button onClick={savePlan} className="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><Save className="h-4 w-4" /> Salvar revisão</button></div>{status && <p className="mt-4 text-sm text-muted-foreground">{status}</p>}<p className="mt-4 text-xs text-muted-foreground">{plan.version}</p></header>
    <section className={box}><Title icon={Target} text="Resumo executivo" /><p className="mt-4 max-w-5xl text-sm leading-relaxed">{plan.executiveSummary}</p><div className="mt-5 grid gap-3 md:grid-cols-4"><Summary label="Especialidade" value={plan.positioning.specialty} /><Summary label="Oferta" value={plan.positioning.offer} /><Summary label="Público" value={plan.positioning.audience} /><Summary label="Diferencial" value={plan.positioning.differentiator} /></div></section>
    <section className={box}><Title text="O que este plano considera da metodologia" /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{plan.methodologyBasis.map((item) => <CheckItem key={item} text={item} />)}</div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className={box}><Title text="Diagnóstico do negócio" /><p className="mt-4 text-sm">{plan.businessDiagnosis.context}</p><Subheading text="Linha de base" /><List items={plan.businessDiagnosis.baseline} /><Subheading text="Restrições a respeitar" /><List items={plan.businessDiagnosis.constraints} /><Subheading text="Ainda não sabemos" /><List items={plan.businessDiagnosis.unknowns} muted /></section><section className={box}><Title text="Posicionamento e oferta" /><Subheading text="Promessa" /><p className="text-sm leading-relaxed">{plan.positioning.promise}</p><Subheading text="Transformação" /><p className="text-sm leading-relaxed">{plan.offerArchitecture.transformation}</p><Subheading text="Mecanismo" /><p className="text-sm leading-relaxed">{plan.offerArchitecture.mechanism}</p><Subheading text="Próximo passo" /><p className="text-sm leading-relaxed">{plan.offerArchitecture.nextStep}</p></section></div>
    <section className={box}><Title text="Pesquisa de mercado e benchmarking" /><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><Subheading text="Estado atual" /><p className="text-sm">Pesquisa: <strong>{plan.market.researchStatus}</strong>. Consciência predominante: <strong>{plan.market.awareness}</strong>.</p><Subheading text="Perguntas obrigatórias" /><List items={plan.market.questions} /></div><div><Subheading text="O que coletar" /><List items={plan.market.benchmarkInputs} /><div className="mt-4 rounded-xl bg-primary/5 p-4 text-sm leading-relaxed"><strong>Regra:</strong> {plan.market.decision}</div></div></div></section>
    <section className={box}><Title text="Arquitetura da oferta" /><div className="mt-4 grid gap-5 lg:grid-cols-3"><div><Subheading text="Provas necessárias" /><List items={plan.offerArchitecture.proof} /></div><div><Subheading text="Incluído na entrega" /><List items={plan.offerArchitecture.scope} /></div><div><Subheading text="Fora do escopo sem contratação" /><List items={plan.offerArchitecture.exclusions} muted /></div></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className={box}><Title text="Prioridades de intervenção" /><div className="mt-4 space-y-3">{plan.priorities.length ? plan.priorities.map((priority) => <div key={priority.dimension} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-primary">Prioridade {priority.rank}</span><h3 className="mt-1 font-semibold">{priority.dimension}</h3></div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">{priority.metric}</span></div><p className="mt-3 text-sm text-muted-foreground">{priority.problem}</p><List items={priority.actions} /></div>) : <p className="text-sm text-muted-foreground">Preencha o diagnóstico para priorizar intervenções.</p>}</div></section><section className={box}><Title text="Aquisição e criativos" /><Subheading text="Rotas de aquisição" /><List items={plan.acquisition.channels} /><Subheading text="Ativo/funil de entrada" /><p className="text-sm">{plan.acquisition.asset}</p><Subheading text="Briefing de criativo" /><List items={plan.acquisition.creativeBrief} /><Subheading text="Regra de teste" /><p className="text-sm leading-relaxed">{plan.acquisition.campaignRule}</p><p className="mt-3 text-xs text-muted-foreground">{plan.acquisition.budgetNote}</p></section></div>
    <section className={box}><Title text="Funil recomendado e critérios de passagem" /><div className="mt-4 space-y-3">{plan.funnel.stagesDetail.map((stage, index) => <div key={stage.name} className="rounded-xl border border-border p-4"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">{index + 1}</span><h3 className="font-semibold">{stage.name}</h3><span className="ml-auto text-xs text-muted-foreground">{stage.owner}</span></div><p className="mt-2 text-sm">{stage.purpose}</p><div className="mt-3 grid gap-3 text-xs text-muted-foreground sm:grid-cols-3"><p><strong>Entrada:</strong> {stage.entryEvidence}</p><p><strong>Saída:</strong> {stage.exitEvidence}</p><p><strong>SLA:</strong> {stage.sla}</p></div></div>)}</div><p className="mt-4 rounded-xl bg-primary/5 p-4 text-sm"><strong>Primeira ação:</strong> {plan.funnel.firstAction}<br /><strong>Handoff:</strong> {plan.funnel.handoff}</p></section>
    <section className={box}><Title text="Processo comercial e vendas" /><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><Subheading text="Papéis" /><List items={plan.commercialProcess.roles} /><Subheading text="Cadência e rituais" /><List items={plan.commercialProcess.cadence} /></div><div><Subheading text="Estrutura da call" /><List items={plan.commercialProcess.callStructure} /><Subheading text="Objeções para investigar" /><List items={plan.commercialProcess.objections} /></div></div><div className="mt-5 rounded-xl bg-muted/40 p-4"><Subheading text="Handoff para entrega" /><List items={plan.commercialProcess.handoff} /></div></section>
    <section className={box}><Title text="Plano de implementação em 90 dias" /><div className="mt-4 grid gap-3 md:grid-cols-3">{plan.ninetyDays.map((period) => <div key={period.period} className="rounded-xl bg-muted/40 p-4"><p className="text-xs font-semibold text-primary">{period.period}</p><h3 className="mt-2 font-semibold">{period.objective}</h3><List items={period.actions} /><p className="mt-3 border-t border-border pt-3 text-xs text-muted-foreground"><strong>Aceite:</strong> {period.acceptance}</p></div>)}</div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className={box}><Title text="Indicadores" /><div className="mt-4 grid gap-2 sm:grid-cols-2">{plan.indicators.map((indicator) => <CheckItem key={indicator} text={indicator} />)}</div></section><section className={box}><Title icon={ShieldCheck} text="Governança e limites" /><Subheading text="Aprovações" /><List items={plan.governance.approvals} /><Subheading text="Automação" /><List items={plan.governance.automations} /><Subheading text="Compliance" /><List items={plan.governance.compliance} /></section></div>
    <section className="rounded-2xl border border-amber-500/30 bg-amber-500/5 p-6"><h2 className="font-semibold">Evidências ainda necessárias antes da aprovação</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{plan.evidenceNeeded.map((item) => <p key={item} className="text-sm text-muted-foreground">• {item}</p>)}</div></section>
  </main>;
}

function Title({ icon: Icon, text }: { icon?: typeof Target; text: string }) { return <div className="flex items-center gap-2">{Icon && <Icon className="h-5 w-5 text-primary" />}<h2 className="font-semibold">{text}</h2></div>; }
function Subheading({ text }: { text: string }) { return <h3 className="mb-2 mt-5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{text}</h3>; }
function List({ items, muted = false }: { items: string[]; muted?: boolean }) { return <ul className={`mt-2 space-y-2 text-sm ${muted ? "text-muted-foreground" : ""}`}>{items.map((item) => <li key={item}>• {item}</li>)}</ul>; }
function CheckItem({ text }: { text: string }) { return <div className="flex items-start gap-2 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{text}</div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-muted/40 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
