"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ChevronDown, ShieldCheck, Sparkles } from "lucide-react";
import { COMMERCIAL_PLAYBOOKS, type Playbook, recommendPlaybooks } from "@/lib/commercial/playbooks";

export default function CommercialPlaybooksPage() {
  const [playbooks, setPlaybooks] = useState<Playbook[]>(COMMERCIAL_PLAYBOOKS);
  const [scores, setScores] = useState<Record<string, number>>({});
  const [creating, setCreating] = useState(false);
  const [created, setCreated] = useState(0);
  useEffect(() => { void fetch("/api/commercial/onboarding").then((response) => response.json()).then((data) => { const latest = data.assessments?.[0]; if (latest?.dimension_scores) { setScores(latest.dimension_scores); setPlaybooks(recommendPlaybooks(latest.dimension_scores)); } }); }, []);
  async function createDrafts() { setCreating(true); let total = 0; for (const playbook of playbooks) { const template = playbook.id === "new-lead" ? "health_lead_intake" : playbook.id === "appointment" ? "appointment_confirmation" : playbook.id === "post-plan" ? "plan_follow_up" : null; if (!template) continue; const response = await fetch("/api/automations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ template, name: `${playbook.name} — rascunho`, description: playbook.objective, is_active: false }) }); if (response.ok) total += 1; } setCreated(total); setCreating(false); }
  return <main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-8"><Link href="/commercial" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Voltar ao comando comercial</Link><header className="rounded-2xl border border-border bg-card p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><Sparkles className="mt-1 h-6 w-6 text-primary" /><div><p className="text-sm font-medium text-primary">Playbooks comerciais</p><h1 className="mt-1 text-2xl font-bold">Recomendações para a operação</h1><p className="mt-2 text-sm text-muted-foreground">Modelos adaptáveis para serviços high-ticket. Eles são sugestões revisáveis antes de qualquer automação.</p></div></div><button onClick={createDrafts} disabled={creating} className="inline-flex h-10 shrink-0 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">{creating ? "Gerando…" : "Gerar rascunhos"}</button></div>{Object.keys(scores).length > 0 && <p className="mt-4 rounded-lg bg-primary/5 p-3 text-sm">A lista abaixo foi priorizada com base no diagnóstico mais recente.</p>}{created > 0 && <p className="mt-3 text-sm text-emerald-600">{created} rascunho(s) criado(s). Revise em Automações antes de ativar.</p>}</header><div className="space-y-3">{playbooks.map((playbook) => <PlaybookCard key={playbook.id} playbook={playbook} />)}</div></main>;
}

function PlaybookCard({ playbook }: { playbook: Playbook }) { const [open, setOpen] = useState(false); return <section className="rounded-2xl border border-border bg-card p-5"><button className="flex w-full items-start justify-between gap-4 text-left" onClick={() => setOpen((value) => !value)}><div><div className="flex items-center gap-2"><h2 className="font-semibold">{playbook.name}</h2><span className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary">Prioridade {playbook.priority}</span></div><p className="mt-1 text-sm text-muted-foreground">{playbook.objective}</p><p className="mt-2 text-xs text-muted-foreground">Gatilho: {playbook.trigger}</p></div><ChevronDown className={`h-5 w-5 shrink-0 transition-transform ${open ? "rotate-180" : ""}`} /></button>{open && <div className="mt-5 grid gap-4 border-t border-border pt-4 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Etapas</p><ol className="mt-2 space-y-2 text-sm">{playbook.steps.map((step, index) => <li key={step}><span className="mr-2 text-xs font-semibold text-primary">{index + 1}.</span>{step}</li>)}</ol></div><div className="rounded-xl bg-amber-500/5 p-4 text-sm"><div className="flex gap-2"><ShieldCheck className="h-4 w-4 shrink-0 text-amber-600" /><p>{playbook.guardrail}</p></div></div></div>}</section>; }
