"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, ChevronRight, GitBranch, Target } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { FUNNEL_TEMPLATES, getFunnelTemplate, validateFunnelDraft, type FunnelStageTemplate, type FunnelTemplate } from "@/lib/commercial/funnels";

type StageDraft = FunnelStageTemplate & { sla_hours: number; probability: number; exit_criteria: string };

export default function FunnelBuilderPage() {
  const supabase = createClient();
  const { accountId } = useAuth();
  const [templateId, setTemplateId] = useState(FUNNEL_TEMPLATES[0].id);
  const template = getFunnelTemplate(templateId);
  const [step, setStep] = useState(1);
  const [name, setName] = useState(template.name);
  const [offer, setOffer] = useState("");
  const [stages, setStages] = useState<StageDraft[]>(() => toDrafts(template));
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");
  const validationIssues = useMemo(() => validateFunnelDraft(name, stages), [name, stages]);

  const completion = useMemo(() => Math.round((step / 3) * 100), [step]);
  function chooseTemplate(next: FunnelTemplate) { setTemplateId(next.id); setName(next.name); setStages(toDrafts(next)); setStep(1); setSaved(false); setError(""); }
  function updateStage(index: number, patch: Partial<StageDraft>) { setStages((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  async function createFunnel() {
    setError(""); setSaving(true);
    if (!accountId || !name.trim()) { setError("Informe um nome e verifique se sua conta está carregada."); setSaving(false); return; }
    if (validationIssues.length > 0) { setError(`Revise a arquitetura antes de salvar: ${validationIssues[0].message}`); setSaving(false); return; }
    const { data: auth } = await supabase.auth.getUser();
    if (!auth.user) { setError("Sua sessão expirou. Entre novamente para criar o funil."); setSaving(false); return; }
    const architecture = { templateId, objective: template.objective, promise: template.promise, trafficSources: template.trafficSources, assets: template.assets, strategy: template.strategy, dependencies: template.dependencies, metrics: template.metrics, messageSequence: template.messageSequence, checklist: template.checklist, offer: offer.trim() || null, version: 1 };
    let { data: pipeline, error: pipelineError } = await supabase.from("pipelines").insert({ name: name.trim(), user_id: auth.user.id, account_id: accountId, funnel_template_id: templateId, funnel_metadata: architecture, strategy_status: "draft" }).select("id").single();
    // The migration is intentionally deployable independently. Until it reaches a remote database,
    // preserve the old creation path instead of breaking the CRM.
    if (pipelineError?.code === "42703" || pipelineError?.code === "PGRST204") ({ data: pipeline, error: pipelineError } = await supabase.from("pipelines").insert({ name: name.trim(), user_id: auth.user.id, account_id: accountId }).select("id").single());
    if (pipelineError || !pipeline) { setError(pipelineError?.message || "Não foi possível criar o funil."); setSaving(false); return; }
    const { error: stagesError } = await supabase.from("pipeline_stages").insert(stages.map((stage, position) => ({ name: stage.name, sla_hours: stage.sla_hours, probability: stage.probability, exit_criteria: stage.exit_criteria, pipeline_id: pipeline.id, position, color: ["#3b82f6", "#06b6d4", "#eab308", "#f97316", "#a855f7", "#22c55e"][position % 6] })));
    if (stagesError) { setError(stagesError.message); setSaving(false); return; }
    setSaved(true); setSaving(false);
  }

  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-8"><Link href="/commercial" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Voltar ao comando comercial</Link><header className="rounded-2xl border border-border bg-card p-6"><div className="flex items-start gap-3"><GitBranch className="mt-1 h-6 w-6 text-primary" /><div><p className="text-sm font-medium text-primary">Criador de funil · baseado na metodologia</p><h1 className="mt-1 text-2xl font-bold">Escolha a arquitetura antes de criar etapas</h1><p className="mt-2 max-w-4xl text-sm leading-relaxed text-muted-foreground">Funil não é apenas uma sequência no CRM. É uma estratégia que define quem entra, que evidência permite avançar, quem age, qual mensagem é usada, o que é medido e qual saída acontece quando não há aderência.</p></div></div><div className="mt-6 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary transition-all" style={{ width: `${completion}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">Passo {step} de 3 · modelo, arquitetura e criação</p></header>{saved ? <section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-6"><div className="flex items-start gap-3"><Check className="h-6 w-6 text-emerald-600" /><div><h2 className="font-semibold">Funil criado com sucesso</h2><p className="mt-1 text-sm text-muted-foreground">As etapas foram salvas no CRM. Mensagens e automações continuam desativadas até revisão.</p><Link href="/pipelines" className="mt-4 inline-flex h-10 items-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Abrir Pipelines</Link></div></div></section> : <><section className="rounded-2xl border border-border bg-card p-6">{step === 1 && <TemplateStep template={template} selected={templateId} onChoose={chooseTemplate} />}{step === 2 && <ArchitectureStep template={template} stages={stages} updateStage={updateStage} />}{step === 3 && <ReviewStep template={template} name={name} offer={offer} stages={stages} error={error} issues={validationIssues} setName={setName} setOffer={setOffer} />}</section><div className="flex justify-between"><button type="button" disabled={step === 1} onClick={() => setStep((value) => value - 1)} className="h-10 rounded-md border border-input px-4 text-sm disabled:opacity-50">Voltar</button>{step < 3 ? <button type="button" onClick={() => setStep((value) => value + 1)} className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Continuar <ChevronRight className="h-4 w-4" /></button> : <button type="button" onClick={createFunnel} disabled={saving || validationIssues.length > 0} className="h-10 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50">{saving ? "Criando…" : validationIssues.length > 0 ? "Corrija a revisão" : "Criar funil no CRM"}</button>}</div></>}</main>;
}

function TemplateStep({ template, selected, onChoose }: { template: FunnelTemplate; selected: string; onChoose: (template: FunnelTemplate) => void }) { return <div className="space-y-6"><div><h2 className="text-lg font-semibold">1. Qual modelo de jornada faz sentido?</h2><p className="mt-1 text-sm text-muted-foreground">A escolha depende da consciência, do ticket, da complexidade da oferta e da capacidade comercial. Não existe um funil universal.</p></div><div className="grid gap-3 md:grid-cols-2">{FUNNEL_TEMPLATES.map((item) => <button key={item.id} type="button" onClick={() => onChoose(item)} className={`rounded-xl border p-4 text-left transition ${item.id === selected ? "border-primary bg-primary/5 ring-1 ring-primary" : "border-border hover:bg-muted/50"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-primary">{item.category}</p><h3 className="mt-1 font-semibold">{item.name}</h3><p className="mt-2 text-sm text-muted-foreground">{item.bestFor}</p></div><Target className="h-5 w-5 shrink-0 text-primary" /></div></button>)}</div><div className="grid gap-5 lg:grid-cols-2"><InfoBlock title="Objetivo do modelo" text={template.objective} /><InfoList title="Fontes de tráfego" items={template.trafficSources} /><InfoList title="Ativos necessários" items={template.assets} /><InfoList title="Dependências" items={template.dependencies} /></div><InfoList title="Estratégia de uso" items={template.strategy} /></div>; }

function ArchitectureStep({ template, stages, updateStage }: { template: FunnelTemplate; stages: StageDraft[]; updateStage: (index: number, patch: Partial<StageDraft>) => void }) { return <div className="space-y-6"><div><h2 className="text-lg font-semibold">2. Revise a arquitetura e os critérios</h2><p className="mt-1 text-sm text-muted-foreground">Cada etapa precisa ter propósito, evidência de entrada, evidência de saída, dono, prazo, campos, eventos e automação permitida.</p></div><div className="rounded-xl bg-primary/5 p-4 text-sm"><strong>Promessa da arquitetura:</strong> {template.promise}</div><div className="space-y-4">{stages.map((stage, index) => <article key={`${stage.name}-${index}`} className="rounded-xl border border-border p-4"><div className="flex items-start gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{index + 1}</span><div className="min-w-0 flex-1 space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_160px_160px]"><label className="text-xs font-medium text-muted-foreground">Nome<input value={stage.name} onChange={(event) => updateStage(index, { name: event.target.value })} className="mt-1 h-9 w-full rounded-md border border-input bg-background px-3 text-sm font-medium" /></label><label className="text-xs font-medium text-muted-foreground">SLA (horas)<input type="number" min={1} value={stage.sla_hours} onChange={(event) => updateStage(index, { sla_hours: Number(event.target.value) })} className="mt-1 h-9 w-full rounded-md border border-input bg-background px-2 text-sm" /></label><label className="text-xs font-medium text-muted-foreground">Probabilidade (%)<input type="number" min={0} max={100} value={stage.probability} onChange={(event) => updateStage(index, { probability: Number(event.target.value) })} className="mt-1 h-9 w-full rounded-md border border-input bg-background px-2 text-sm" /></label></div><p className="text-sm"><strong>Propósito:</strong> {stage.purpose}</p><div className="grid gap-3 md:grid-cols-2"><p className="text-sm"><strong>Entrada:</strong> {stage.entryCriteria}</p><p className="text-sm"><strong>Saída:</strong> {stage.exitCriteria}</p></div><div className="grid gap-3 md:grid-cols-3 text-xs text-muted-foreground"><p><strong>Dono:</strong> {stage.owner}</p><p><strong>Eventos:</strong> {stage.events.join(", ")}</p><p><strong>Automação:</strong> {stage.automation}</p></div><p className="text-xs text-muted-foreground"><strong>Campos:</strong> {stage.requiredFields.join(" · ")}</p><label className="block text-xs font-medium text-muted-foreground">Critério final ajustado<input value={stage.exit_criteria} onChange={(event) => updateStage(index, { exit_criteria: event.target.value })} className="mt-1 h-9 w-full rounded-md border border-input bg-background px-3 text-sm" /></label></div></div></article>)}</div><InfoList title="Checklist de implantação" items={template.checklist} /></div>; }

function ReviewStep({ template, name, offer, stages, error, issues, setName, setOffer }: { template: FunnelTemplate; name: string; offer: string; stages: StageDraft[]; error: string; issues: { path: string; message: string }[]; setName: (value: string) => void; setOffer: (value: string) => void }) { return <div className="space-y-6"><div><h2 className="text-lg font-semibold">3. Dê nome, associe a oferta e confirme</h2><p className="mt-1 text-sm text-muted-foreground">A criação grava a arquitetura escolhida como rascunho. Nenhuma mensagem será ativada automaticamente.</p></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Nome do funil<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3" /></label><label className="text-sm font-medium">Oferta principal<input value={offer} onChange={(event) => setOffer(event.target.value)} placeholder="Ex.: Implantação comercial high-ticket" className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3" /></label></div><div className="rounded-xl bg-muted/40 p-4 text-sm"><p><strong>Modelo:</strong> {template.name}</p><p className="mt-1"><strong>Etapas:</strong> {stages.length}</p><p className="mt-1"><strong>Ativos:</strong> {template.assets.join(" · ")}</p></div><div className="grid gap-5 lg:grid-cols-2"><InfoList title="Mensagens previstas" items={template.messageSequence.map((item) => `${item.moment}: ${item.goal}`)} /><div><p className="text-sm font-semibold">Métricas e decisões</p><ul className="mt-2 space-y-2 text-sm text-muted-foreground">{template.metrics.map((metric) => <li key={metric.name}>• <strong>{metric.name}:</strong> {metric.formula} — {metric.decision}</li>)}</ul></div></div>{issues.length > 0 && <div className="rounded-md border border-amber-500/40 bg-amber-500/10 p-3 text-sm"><p className="font-semibold">A revisão encontrou pontos que precisam de atenção</p><ul className="mt-2 space-y-1 text-muted-foreground">{issues.slice(0, 6).map((issue, index) => <li key={`${issue.path}-${index}`}>• {issue.message}</li>)}</ul></div>}{error && <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}</div>; }

function toDrafts(template: FunnelTemplate): StageDraft[] { return template.stages.map((item) => ({ ...item, sla_hours: item.slaHours, probability: item.probability, exit_criteria: item.exitCriteria })); }
function InfoBlock({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</p><p className="mt-2 text-sm leading-relaxed">{text}</p></div>; }
function InfoList({ title, items }: { title: string; items: string[] }) { return <div className="rounded-xl border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</p><ul className="mt-2 space-y-2 text-sm text-muted-foreground">{items.map((item) => <li key={item}>• {item}</li>)}</ul></div>; }
