'use client';
import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';

export function GhlImport() {
  const [locationId, setLocationId] = useState(''); const [token, setToken] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function configureAndImport() { setBusy(true); setMessage(''); try { const configured = await fetch('/api/integrations/ghl', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ location_id: locationId, access_token: token }) }); const configBody = await configured.json(); if (!configured.ok) throw new Error(configBody.error ?? 'Não foi possível configurar o GHL'); const imported = await fetch('/api/integrations/ghl/import', { method: 'POST' }); const body = await imported.json(); if (!imported.ok) throw new Error(body.error ?? 'Não foi possível importar'); setMessage(`${body.data.imported} contatos importados; ${body.data.skipped} já estavam atualizados.`); setToken(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro na importação'); } finally { setBusy(false); } }
  return <section className="mt-6 rounded-xl border border-border bg-card p-5"><div className="flex items-start gap-3"><Download className="mt-0.5 h-5 w-5 text-primary" /><div className="min-w-0 flex-1"><h2 className="font-medium">Transição do GoHighLevel</h2><p className="mt-1 text-sm text-muted-foreground">Importe contatos do GHL para continuar trabalhando enquanto o WACRM amadurece. A importação é incremental e não duplica registros.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input aria-label="Location ID do GHL" value={locationId} onChange={(event) => setLocationId(event.target.value)} placeholder="Location ID" className="h-10 rounded-md border bg-background px-3 text-sm" /><input aria-label="Token privado do GHL" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Private Integration Token" type="password" className="h-10 rounded-md border bg-background px-3 text-sm" /></div><button type="button" disabled={busy || !locationId || !token} onClick={configureAndImport} className="mt-4 inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />} Importar do GHL</button>{message && <p className="mt-3 text-sm text-muted-foreground" role="status">{message}</p>}</div></div></section>;
}
